IVRControlPanel/Controllers/ProfileImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IVRControlPanel.Models;
using System.Drawing;
using System.IO;
using System.Drawing.Drawing2D;
using System.Net;
using System.Text.RegularExpressions;

namespace IVRControlPanel.Controllers
{
    [Authorize]
    public class ProfileImageController : Controller
    {
        //
        // GET: /ProfileImage/

        public ActionResult Index()
        {
            var images = new ImagesModel();
            //Read out files from the files directory
            var files = Directory.GetFiles(Server.MapPath("~/Content/img"));
            //Add them to the model
            foreach (var file in files)
                images.Images.Add(Path.GetFileName(file));

            return View(images);
        }


        //
        // GET: /Home/UploadImage

        public ActionResult UploadImage()
        {
            return View();
        }

        //
        // POST: /Home/UploadImage

        [HttpPost]
        public ActionResult UploadImage(UploadImageModel model)
        {
            //Check if all simple data annotations are valid
            if (ModelState.IsValid)
            {
                //Prepare the needed variables
                Bitmap original = null;
                var name = "newimagefile";
                var errorField = string.Empty;

                if (model.IsUrl)
                {
                    errorField = "Url";
                    name = GetUrlFileName(model.Url);
                    original = GetImageFromUrl(model.Url);
                }
                else if (model.IsFlickr)
                {
                    errorField = "Flickr";
                    name = GetUrlFileName(model.Flickr);
                    original = GetImageFromUrl(model.Flickr);
                }
                else if (model.File != null) // model.IsFile
                {
                    errorField = "File";
                    name = Path.GetFileNameWithoutExtension(Regex.Replace(model.File.FileName, "[^a-zA-Z0-9_.]", string.Empty));
                    name = DateTime.Now.ToString("yyyyMMddhhmmss") + name;

                    //Path.GetFileNameWithoutExtension(model.File.FileName);
                    original = Bitmap.FromStream(model.File.InputStream) as Bitmap;
                }

                //If we had success so far
                if (original != null)
                {
                    var img = CreateImage(original, model.X, model.Y, model.Width, model.Height);

                    //Demo purposes only - save image in the file system
                    var fn = Server.MapPath("~/Content/img/profile/" + name + ".jpg");
                    img.Save(fn, System.Drawing.Imaging.ImageFormat.Jpeg);
                    
                    // Save Image to the database
                    foreach (string upload in Request.Files)
                    {
                        string mimeType = Request.Files[upload].ContentType;
                        Stream fileStream = Request.Files[upload].InputStream;
                        string fileName = Path.GetFileNameWithoutExtension(Regex.Replace(Request.Files[upload].FileName, "[^a-zA-Z0-9_.]", string.Empty)) + ".jpg";
                        int fileLength = Request.Files[upload].ContentLength;
                        byte[] fileData = new byte[fileLength];
                        fileStream.Read(fileData, 0, fileLength);

                        IVRControlPanelEntities db = new IVRControlPanelEntities();
                        var result = from u in db.Users where (u.UserName == User.Identity.Name) select u;

                        if (result.Count() != 0)
                        {
                            var dbuser = result.First();

                            dbuser.FileContent = fileData;
                            dbuser.MimeType = mimeType;
                            dbuser.FileName = name + ".jpg";
                            db.SaveChanges();
                        }
                    }

                    //Redirect to index
                    return RedirectToAction("Details","UserProfile");
                }
                else //Otherwise we add an error and return to the (previous) view with the model data
                    ModelState.AddModelError(errorField, "Your upload did not seem valid. Please try again using only correct images!");
            }

            return View(model);
        }

        /// <summary>
        /// Gets an image from the specified URL.
        /// </summary>
        /// <param name="url">The URL containing an image.</param>
        /// <returns>The image as a bitmap.</returns>
        Bitmap GetImageFromUrl(string url)
        {
            var buffer = 1024;
            Bitmap image = null;

            if (!Uri.IsWellFormedUriString(url, UriKind.Absolute))
                return image;

            using (var ms = new MemoryStream())
            {
                var req = WebRequest.Create(url);

                using (var resp = req.GetResponse())
                {
                    using (var stream = resp.GetResponseStream())
                    {
                        var bytes = new byte[buffer];
                        var n = 0;

                        while ((n = stream.Read(bytes, 0, buffer)) != 0)
                            ms.Write(bytes, 0, n);
                    }
                }

                image = Bitmap.FromStream(ms) as Bitmap;
            }

            return image;
        }

        /// <summary>
        /// Gets the filename that is placed under a certain URL.
        /// </summary>
        /// <param name="url">The URL which should be investigated for a file name.</param>
        /// <returns>The file name.</returns>
        string GetUrlFileName(string url)
        {
            var parts = url.Split(new char[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
            var last = parts[parts.Length - 1];
            return Path.GetFileNameWithoutExtension(last);
        }

        /// <summary>
        /// Creates a small image out of a larger image.
        /// </summary>
        /// <param name="original">The original image which should be cropped (will remain untouched).</param>
        /// <param name="x">The value where to start on the x axis.</param>
        /// <param name="y">The value where to start on the y axis.</param>
        /// <param name="width">The width of the final image.</param>
        /// <param name="height">The height of the final image.</param>
        /// <returns>The cropped image.</returns>
        Bitmap CreateImage(Bitmap original, int x, int y, int width, int height)
        {
            var img = new Bitmap(width, height);

            using (var g = Graphics.FromImage(img))
            {
                g.SmoothingMode = SmoothingMode.AntiAlias;
                g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                g.DrawImage(original, new Rectangle(0, 0, width, height), x, y, width, height, GraphicsUnit.Pixel);
            }

            return img;
        }

    }
}

IVRControlPanel/Views/ProfileImage/Index.cshtml
@model IVRControlPanel.Models.ImagesModel
@{
    ViewBag.Title = "Home Page";
}
<h2>List of images</h2>
<p>
    This page contains the list of all uploaded images.
</p>
@if (Model.Images.Count > 0)
{
<div class="imageContainer">
@foreach (var src in Model.Images)
{
    <div class="imageBox">
        <a href="@Url.Content("~/Content/img/" + src)" target="_blank"><img src="@Url.Content("~/Content/img/" + src)" alt="Image" class="imagePreview" /></a>
    </div>
}
</div>
}
else
{
<div class="imageCenter">
    No images have been uploaded so far. @Html.ActionLink("Click here", "UploadImage") to upload an image.
</div>
}
<div class="clear"></div>

IVRControlPanel/Views/ProfileImage/UploadImage.cshtml
@model IVRControlPanel.Models.UploadImageModel
@{
    ViewBag.Title = "Change Profile Image";
}
@section Styles
{
    <link href="@Url.Content("~/Content/ImageArea.css")" rel="stylesheet" />
}
@section Scripts
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"  type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.imgareaselect.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            //Get the checkboxes and disable them
            var boxes = $('input[type=checkbox]').attr('disabled', true);

            //Get the preview image and set the onload event handler
            var preview = $('#preview').load(function () {
                setPreview();
                ias.setOptions({
                    x1: 0,
                    y1: 0,
                    x2: $(this).width(),
                    y2: $(this).height(),
                    show: true
                });
            });

            //Set the 4 coordinates for the cropping
            var setPreview = function (x, y, w, h) {
                $('#X').val(x || 0);
                $('#Y').val(y || 0);
                $('#Width').val(w || preview[0].naturalWidth);
                $('#Height').val(h || preview[0].naturalHeight);
            };

            //Initialize the image area select plugin
            var ias = preview.imgAreaSelect({
                handles: true,
                instance: true,
                parent: 'body',
                onSelectEnd: function (s, e) {
                    var scale = preview[0].naturalWidth / preview.width();
                    var _f = Math.floor;
                    setPreview(_f(scale * e.x1), _f(scale * e.y1), _f(scale * e.width), _f(scale * e.height));
                }
            });

            //Check one of the checkboxes
            var setBox = function (filter) {
                $('button').attr('disabled', false);
                boxes.attr('checked', false)
            .filter(filter).attr({ 'checked': true, 'disabled': false });
            };

            //Initial state of X, Y, Width and Height is 0 0 1 1
            setPreview(0, 0, 1, 1);

            //Fetch Flickr images
            var fetchImages = function (query) {
                $.getJSON('http://www.flickr.com/services/feeds/photos_public.gne?jsoncallback=?', {
                    tags: query,
                    tagmode: "any",
                    format: "json"
                }, function (data) {
                    var screen = $('<div />').addClass('waitScreen').click(function () {
                        $(this).remove();
                    }).appendTo('body');
                    var box = $('<div />').addClass('flickrImages').appendTo(screen);
                    $.each(data.items, function (i, v) {
                        console.log(data.items[i]);
                        $('<img />').addClass('flickrImage').attr('src', data.items[i].media.m).click(function () {
                            $('#Flickr').val(this.src).change();
                            screen.remove();
                        }).appendTo(box);
                    });
                });
            };

            //Flickr
            $('#FlickrQuery').change(function () {
                fetchImages(this.value);
            });

            $('#Flickr').change(function () {
                setBox('#IsFlickr');
                preview.attr('src', this.value);
            });

            //What happens if the URL changes?
            $('#Url').change(function () {
                setBox('#IsUrl');
                preview.attr('src', this.value);
            });

            //What happens if the File changes?
            $('#File').change(function (evt) {
                var f = evt.target.files[0];
                var reader = new FileReader();

                if (!f.type.match('image.*')) {
                    alert("The selected file does not appear to be an image.");
                    return;
                }

                setBox('#IsFile');
                reader.onload = function (e) { preview.attr('src', e.target.result); };
                reader.readAsDataURL(f);
            });

            //What happens if any checkbox is checked ?!
            boxes.change(function () {
                setBox(this);
                $('#' + this.id.substr(2)).change();
            });

            $('button').attr('disabled', true);
            $('form').submit(function () {
                $('button').attr('disabled', true).text('Please wait ...');
            });
        });
    </script>
}
<div class="grid_12">
    <div class="box">
        <header>
            <div class="inner">
                <div class="left title">
                    <h1>
                        Change Profile Image</h1>
                </div>
                <div class="right">
                    <a href="#" class="close">close</a>
                </div>
            </div>
        </header>
        <div class="box-content">
            @using (Html.BeginForm("UploadImage", "ProfileImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(model => model.X)
                @Html.HiddenFor(model => model.Y)
                @Html.HiddenFor(model => model.Width)
                @Html.HiddenFor(model => model.Height)
                @Html.HiddenFor(model => model.Flickr)
                <div id="upload-choices">
                    <div class="field">
                        <label>
                            @Html.EditorFor(model => model.IsUrl) Internet Url</label>
                        @Html.EditorFor(model => model.Url)
                        @Html.ValidationMessageFor(model => model.Url)
                    </div>
                    <div class="field">
                        <label>
                            @Html.EditorFor(model => model.IsFlickr) Flickr Image
                        </label>
                        @Html.Editor("FlickrQuery")
                        @Html.ValidationMessageFor(model => model.Flickr)
                    </div>
                    <div class="field">
                        <label>
                            @Html.EditorFor(model => model.IsFile) Local File
                        </label>
                        <input id="File" type="file" name="File" class="custom-file-input" />
                        @Html.ValidationMessageFor(model => model.File)
                    </div>
                    <div class="editor-row">
                        @Html.ValidationSummary(true)
                    </div>
                </div>
                <div id="upload-cut">
                    <img alt="Field for image cutting" id="preview" src="@Url.Content("~/Content/empty.png")" />
                </div>
                <footer class="pane">
                    <input type="submit" class="bt blue" value="Upload" />
                </footer>
            }
        </div>
    </div>
</div>